### PR TITLE
Adding LICENSE file to patches directory

### PR DESCRIPTION
**Pull request by NFuture**
Adding missing LICENSE to the patches directory to address https://github.com/ZOSOpenTools/meta/issues/103

### CODE REVIEW

**Comment by MikeFultonDev** [comment]
It’s definitely the right approach but you the names and number of licenses isn’t consistent with other builds we have. Look at m4 and git for examples. There should e a license for our code in the port repo (Apache) and then one license file in each of the patch repositories which should now be stable and dev patches. We are not consistent but should be now that we have proper stable and dev build models

**Comment by NFuture** [comment]
Can you elaborate as to what you meant, @MikeFultonDev  ?. I went through it. And the root has a Apache license and the patches folders have a GNU licence.

**Comment by MikeFultonDev** [comment]
There are a hardware-patches and software-patches license files. We don’t normally have those. Is there a need? Also I think the file name is normally just LICENSE without the .txt extension

**Review by IgorTodorovskiIBM — APPROVED** [review]
We can probably delete software/hardware patches as a follow on. @NFuture are you able to remove the .txt extension? Otherwise it looks good

**Pull request merged**
